#!/usr/bin/env python3
"""Export manuscript figures from the repo's figure notebooks into paper/figures/.

The figure notebooks in ``figures/`` read/write data under ``/wd1/hbito_data/...``
(the UW server), so they only run where that data exists. This script maps each
paper figure to the notebook that generates it and the PNG that notebook writes
(under ``--src-dir``), and copies it into ``paper/figures/`` with the exact
filename the manuscript ``\includegraphics`` expects. With ``--execute`` it runs
each notebook first (via jupyter nbconvert; needs the data + the analysis env).

Run on the machine that has the data:
    pixi run python paper/export_figures.py                 # collect existing PNGs
    pixi run python paper/export_figures.py --execute       # regen notebooks, then collect
    pixi run python paper/export_figures.py --src-dir /path # override output directory

fig02 (pipeline schematic) and fig04 (assembled picking-example panels) have no
single generated source and are maintained by hand -- they are not listed here.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# Default directory the (repointed) figure notebooks save into, relative to the
# repo root (they now read/write ../data/ instead of /wd1). Override with --src-dir.
DEFAULT_SRC_DIR = str(ROOT / "data" / "datasets_all_regions")

# (paper/figures/<dest>, generating notebook, <src>.png the notebook writes in src_dir)
FIGURES = [
    # dest (manuscript name)   ,   generating notebook   ,   src PNG the notebook writes
    # fig1 assembles fig1b.pdf + stas_wo_boundaries.pdf into fig1.pdf (fitz), then
    # rasterizes -> fig1.png (the composite station map the manuscript uses).
    ("fig01_stations.png", "figures/fig01_stations.ipynb", "fig1.png"),
    # fig5 notebook resolves year=all_regions, method=reloc, version=ver3 -> "_cc_" in the
    # written name; the manuscript keeps the pre-cc filename, so src != dest here.
    ("fig03a_qc_rms.png",
     "figures/fig03_qc_histograms.ipynb", "hist_rms_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig03b_qc_p_picks.png",
     "figures/fig03_qc_histograms.ipynb", "hist_p_picks_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig03c_qc_s_picks.png",
     "figures/fig03_qc_histograms.ipynb", "hist_s_picks_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig03d_qc_gaps.png",
     "figures/fig03_qc_histograms.ipynb", "hist_gaps_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    # fig6 = "Earthquake Catalog in the Endeavor" -> the axial/endeavor subregion map
    ("fig08_subregions.png", "figures/fig08_subregions.ipynb",
     "axial_endeavor_events_2010_2015_ver3_cc_nass.png"),
]

# Figures generated by a standalone script (not a notebook):
# (paper/figures/<dest>, script, [args], <src>.png the script writes, dir it writes into)
_MAG = ROOT / "data" / "magnitude"
_PHASE5 = "workflow/06_analysis/phase5_pygmt_map.py"
SCRIPT_FIGURES = [
    # full-margin catalog map (replaces the old fig4)
    ("fig05a_catalog_map.png", _PHASE5, ["--region", "full"],
     "cascadia_ML_map_full.png", _MAG),
    # companion tectonic-context panel: slip deficit, ComCat moment tensors, plate motions
    ("fig05b_context_map.png", _PHASE5, ["--region", "full", "--layer", "context"],
     "cascadia_context_map_full.png", _MAG),
    # regional zoom-ins for comparison with recent region-focused studies
    ("fig06d_blanco.png", _PHASE5, ["--region", "blanco", "--gmrt", "med"],
     "cascadia_ML_map_blanco.png", _MAG),
    ("fig06f_mendocino.png", _PHASE5, ["--region", "mendocino", "--gmrt", "med"],
     "cascadia_ML_map_mendocino.png", _MAG),
    ("fig06a_endeavour.png", _PHASE5, ["--region", "endeavour", "--gmrt", "med"],
     "cascadia_ML_map_endeavour.png", _MAG),
    ("fig06e_gorda.png", _PHASE5, ["--region", "gorda", "--gmrt", "med"],
     "cascadia_ML_map_gorda.png", _MAG),
    ("fig06b_wa_margin.png", _PHASE5, ["--region", "wa_margin", "--gmrt", "med"],
     "cascadia_ML_map_wa_margin.png", _MAG),
    ("fig06c_or_margin.png", _PHASE5, ["--region", "or_margin", "--gmrt", "med"],
     "cascadia_ML_map_or_margin.png", _MAG),
    # Puget Sound with Slab2 interface depth contours (slab-following seismicity)
    ("fig07_puget_slab.png", _PHASE5,
     ["--region", "puget", "--slab-contours", "--legend", "--legend-pos", "TR",
      "--gmrt", "med"],
     "cascadia_ML_map_puget.png", _MAG),
    # supplementary analysis figures
    ("figS01_depth.png", "workflow/06_analysis/phase7_depth_analysis.py", [],
     "depth_analysis.png", _MAG),
    ("figS03_temporal.png", "workflow/06_analysis/phase8_temporal.py", [],
     "temporal_context.png", _MAG),
    ("figS02_megathrust_bucket.png",
     "workflow/06_analysis/phase9_megathrust_bucket.py", [],
     "megathrust_bucket.png", _MAG),
    ("figS04_classification.png",
     "workflow/06_analysis/phase10_event_classification.py", [],
     "event_classification.png", _MAG),
    ("figS05_tremor_crustal.png",
     "workflow/06_analysis/phase11_tremor_crustal.py", [],
     "tremor_crustal.png", _MAG),
    ("figS06_slab_roughness.png",
     "workflow/06_analysis/phase12_slab_roughness.py", [],
     "slab_roughness.png", _MAG),
    ("figS07_tomography.png",
     "workflow/06_analysis/phase13_tomography.py", [],
     "tomography_relation.png", _MAG),
    ("figS08_magnitude_tests.png",
     "workflow/05_magnitude/phase17_routeA_vs_kpos.py", [],
     "routeA_vs_kpos_comparison.png", _MAG),
    ("figS09_completeness.png",
     "workflow/06_analysis/phase14_completeness.py", [],
     "completeness_by_region.png", _MAG),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src-dir", default=DEFAULT_SRC_DIR,
                    help="directory the figure notebooks write PNGs into")
    ap.add_argument("--execute", action="store_true",
                    help="run each generating notebook first (needs data + env)")
    ap.add_argument("--scripts-only", action="store_true",
                    help="with --execute: rerun only the script figures (they need only the "
                         "data products), not the notebooks (they need the /wd1 data)")
    ap.add_argument("--kernel", default="python3",
                    help="Jupyter kernel to run notebooks with (they are saved with a "
                         "'seismo' kernel that isn't registered here; python3 = this env)")
    args = ap.parse_args()
    src_dir = Path(args.src_dir)
    figdir = HERE / "figures"

    if args.execute:
        for nb in ([] if args.scripts_only else sorted({nb for _, nb, _ in FIGURES})):
            print(f"executing {nb} ...")
            r = subprocess.run(["jupyter", "nbconvert", "--to", "notebook",
                                "--execute", "--inplace",
                                f"--ExecutePreprocessor.kernel_name={args.kernel}",
                                str(ROOT / nb)])
            if r.returncode:
                print(f"  WARN {nb} failed to execute (exit {r.returncode}); "
                      "continuing with any PNGs it did write")
        for dest, script, sargs, _src, _sd in SCRIPT_FIGURES:
            print(f"executing {script} {' '.join(sargs)} ...")
            # scripts use paths relative to their own dir -> run from there
            r = subprocess.run(["python", (ROOT / script).name, *sargs],
                               cwd=str((ROOT / script).parent))
            if r.returncode:
                print(f"  WARN {script} {' '.join(sargs)} failed (exit {r.returncode})")

    ok = miss = 0
    collect = [(dest, src_dir / src) for dest, _nb, src in FIGURES]
    collect += [(dest, sd / src) for dest, _sc, _a, src, sd in SCRIPT_FIGURES]
    for dest, s in collect:
        d = figdir / dest
        d.parent.mkdir(parents=True, exist_ok=True)
        if s.exists():
            shutil.copy2(s, d); ok += 1
            print(f"  ok    {dest:58s} <- {s}")
        else:
            miss += 1
            print(f"  MISS  {dest:58s} (not found: {s})")
    print(f"\ncopied {ok}, missing {miss}.  "
          "(fig02 pipeline schematic + fig04 picking panels are maintained by hand.)")
    return 1 if miss else 0


if __name__ == "__main__":
    raise SystemExit(main())
