#!/usr/bin/env python3
"""Export manuscript figures from the repo's figure notebooks into paper/figures/.

The figure notebooks in ``figures/`` read/write data under ``/wd1/hbito_data/...``
(the UW server), so they only run where that data exists. This script maps each
paper figure to the notebook that generates it and the PNG that notebook writes
(under ``--src-dir``), and copies it into ``paper/figures/`` with the exact
filename the manuscript ``\includegraphics`` expects. With ``--execute`` it runs
each notebook first (via jupyter nbconvert; needs the data + the analysis env).

Run on the machine that has the data:
    pixi run python paper/export_figures.py                 # collect existing PNGs
    pixi run python paper/export_figures.py --execute       # regen notebooks, then collect
    pixi run python paper/export_figures.py --src-dir /path # override output directory

fig2 (pipeline schematic) and fig3 (assembled picking-example panels) have no
single generated source and are maintained by hand -- they are not listed here.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# Default directory the (repointed) figure notebooks save into, relative to the
# repo root (they now read/write ../data/ instead of /wd1). Override with --src-dir.
DEFAULT_SRC_DIR = str(ROOT / "data" / "datasets_all_regions")

# (paper/figures/<dest>, generating notebook, <src>.png the notebook writes in src_dir)
FIGURES = [
    # dest (manuscript name)   ,   generating notebook   ,   src PNG the notebook writes
    # fig1 assembles fig1b.pdf + stas_wo_boundaries.pdf into fig1.pdf (fitz), then
    # rasterizes -> fig1.png (the composite station map the manuscript uses).
    ("fig1.png", "figures/fig1_map_stas.ipynb", "fig1.png"),
    ("fig4_cc_no_relief_tremor_contours.png", "figures/fig4_match_events.ipynb",
     "filtered_events_2010_2015_ver3_cc_nass_no_relief_tremor_contours.png"),
    # fig5 notebook resolves year=all_regions, method=reloc, version=ver3 -> "_cc_" in the
    # written name; the manuscript keeps the pre-cc filename, so src != dest here.
    ("fig5_histograms/hist_rms_reloc_cog_ver3_p_4_s_4_rms_2_5.png",
     "figures/fig5_histograms_cc.ipynb", "hist_rms_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig5_histograms/hist_p_picks_reloc_cog_ver3_p_4_s_4_rms_2_5.png",
     "figures/fig5_histograms_cc.ipynb", "hist_p_picks_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig5_histograms/hist_s_picks_reloc_cog_ver3_p_4_s_4_rms_2_5.png",
     "figures/fig5_histograms_cc.ipynb", "hist_s_picks_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    ("fig5_histograms/hist_gaps_reloc_cog_ver3_p_4_s_4_rms_2_5.png",
     "figures/fig5_histograms_cc.ipynb", "hist_gaps_reloc_cog_ver3_cc_p_4_s_4_rms_2_5.png"),
    # fig6 = "Earthquake Catalog in the Endeavor" -> the axial/endeavor subregion map
    ("fig6.png", "figures/fig6_subregions_cc.ipynb",
     "axial_endeavor_events_2010_2015_ver3_cc_nass.png"),
]

# Figures generated by a standalone script (not a notebook):
# (paper/figures/<dest>, script, [args], <src>.png the script writes, dir it writes into)
_MAG = ROOT / "data" / "magnitude"
_PHASE5 = "4_relocation/magnitude/phase5_pygmt_map.py"
SCRIPT_FIGURES = [
    # full-margin catalog map (replaces the old fig4)
    ("fig4_catalog_map.png", _PHASE5, ["--region", "full"],
     "cascadia_ML_map_full.png", _MAG),
    # regional zoom-ins for comparison with recent region-focused studies
    ("fig_regions/blanco.png", _PHASE5, ["--region", "blanco"],
     "cascadia_ML_map_blanco.png", _MAG),
    ("fig_regions/mendocino.png", _PHASE5, ["--region", "mendocino"],
     "cascadia_ML_map_mendocino.png", _MAG),
    ("fig_regions/endeavour.png", _PHASE5, ["--region", "endeavour"],
     "cascadia_ML_map_endeavour.png", _MAG),
    ("fig_regions/gorda.png", _PHASE5, ["--region", "gorda"],
     "cascadia_ML_map_gorda.png", _MAG),
    ("fig_regions/wa_margin.png", _PHASE5, ["--region", "wa_margin"],
     "cascadia_ML_map_wa_margin.png", _MAG),
    ("fig_regions/or_margin.png", _PHASE5, ["--region", "or_margin"],
     "cascadia_ML_map_or_margin.png", _MAG),
    # supplementary analysis figures
    ("supp_depth_analysis.png", "4_relocation/magnitude/phase7_depth_analysis.py", [],
     "depth_analysis.png", _MAG),
    ("supp_temporal_context.png", "4_relocation/magnitude/phase8_temporal.py", [],
     "temporal_context.png", _MAG),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src-dir", default=DEFAULT_SRC_DIR,
                    help="directory the figure notebooks write PNGs into")
    ap.add_argument("--execute", action="store_true",
                    help="run each generating notebook first (needs data + env)")
    ap.add_argument("--kernel", default="python3",
                    help="Jupyter kernel to run notebooks with (they are saved with a "
                         "'seismo' kernel that isn't registered here; python3 = this env)")
    args = ap.parse_args()
    src_dir = Path(args.src_dir)
    figdir = HERE / "figures"

    if args.execute:
        for nb in sorted({nb for _, nb, _ in FIGURES}):
            print(f"executing {nb} ...")
            r = subprocess.run(["jupyter", "nbconvert", "--to", "notebook",
                                "--execute", "--inplace",
                                f"--ExecutePreprocessor.kernel_name={args.kernel}",
                                str(ROOT / nb)])
            if r.returncode:
                print(f"  WARN {nb} failed to execute (exit {r.returncode}); "
                      "continuing with any PNGs it did write")
        for dest, script, sargs, _src, _sd in SCRIPT_FIGURES:
            print(f"executing {script} {' '.join(sargs)} ...")
            # scripts use paths relative to their own dir -> run from there
            r = subprocess.run(["python", (ROOT / script).name, *sargs],
                               cwd=str((ROOT / script).parent))
            if r.returncode:
                print(f"  WARN {script} {' '.join(sargs)} failed (exit {r.returncode})")

    ok = miss = 0
    collect = [(dest, src_dir / src) for dest, _nb, src in FIGURES]
    collect += [(dest, sd / src) for dest, _sc, _a, src, sd in SCRIPT_FIGURES]
    for dest, s in collect:
        d = figdir / dest
        d.parent.mkdir(parents=True, exist_ok=True)
        if s.exists():
            shutil.copy2(s, d); ok += 1
            print(f"  ok    {dest:58s} <- {s}")
        else:
            miss += 1
            print(f"  MISS  {dest:58s} (not found: {s})")
    print(f"\ncopied {ok}, missing {miss}.  "
          "(fig2 pipeline schematic + fig3 picking panels are maintained by hand.)")
    return 1 if miss else 0


if __name__ == "__main__":
    raise SystemExit(main())
